CREATE TABLE IF NOT EXISTS items (
  id CHAR(5) NOT NULL,
  path VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cases (
  id CHAR(4) NOT NULL,
  item CHAR(5) NOT NULL REFERENCES items(id)
);